name: Move Incident Report

on:
  repository_dispatch:
    types:
      - move_incident_report

jobs:
  move-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download incident_report.csv from Report repository
        uses: actions/github-script@v4
        with:
          script: |
            const fs = require('fs');
            const { Octokit } = require('@octokit/core');

            const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

            const { data } = await octokit.request('GET /repos/TeunTycho/Report/actions/artifacts', {
              owner: 'TeunTycho',
              repo: 'Report',
              per_page: 1,
              page: 1,
            });

            const artifact_id = data.artifacts[0].id;
            const download_url = data.artifacts[0].archive_download_url;

            await octokit.request('GET /repos/TeunTycho/Report/actions/artifacts/:artifact_id/zip', {
              owner: 'TeunTycho',
              repo: 'Report',
              artifact_id: artifact_id,
              archive_format: 'zip',
            })
            .then(response => {
              fs.writeFileSync('incident_report.zip', Buffer.from(response.data));
            });

            const unzip = require('unzipper');

            fs.createReadStream('incident_report.zip')
              .pipe(unzip.Extract({ path: 'incident_report' }));
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Move CSV to Security repository
        run: |
          mv incident_report/incident_report.csv .

      - name: Commit and push to Security repository
        run: |
          git add incident_report.csv
          git commit -m "Update incident report CSV"
          git push origin main
